# Generated by Django 5.1.1 on 2024-11-07 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_delete_booking_delete_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant.food', verbose_name='Taom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Izoh qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='review',
            name='profession',
            field=models.CharField(max_length=100, null=True, verbose_name='Kasbi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, "Kamida 1 ta bo'lishi kerak"), django.core.validators.MaxValueValidator(5, "Eng ko'pi 5 ta bo'lishi kerak")], verbose_name='Bahosi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=75, verbose_name='Izoh matni'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
