# Generated by Django 5.1.1 on 2024-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_review_food_alter_review_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ovqat Kategoriyasi', 'verbose_name_plural': 'Ovqat Kategoriyalari'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Ovqat kategoriyasi tavsifi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ovqat kategoriyasi nomi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Oshpaz yoshi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='description',
            field=models.TextField(blank=True, verbose_name='Oshpaz haqida'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='designation',
            field=models.CharField(blank=True, max_length=75, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='image',
            field=models.ImageField(upload_to='chefs/', verbose_name='Oshpaz rasmi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oshpaz ismi'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Oshpaz ismi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(verbose_name='Ovqat haqida'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='food/', verbose_name='Ovqat rasmi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ovqat nomi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ovqat narxi $'),
        ),
    ]
